version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
- Visual Studio 2017
- Ubuntu

configuration:
#- Release
- Debug

platform:
- x64

for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  install:
    - |
      curl -L --silent --show-error -o vulkan-sdk.exe https://vulkan.lunarg.com/sdk/download/1.2.131.2/windows/VulkanSDK-1.2.131.2-Installer.exe?Human=true
      vulkan-sdk.exe /S
      dir C:\VulkanSDK
  build:
    project: GPCS4.sln
    parallel: true
    verbosity: minimal
  after_build:
    - 7z a Debug.7z .\Debug\*
  artifacts:
    - path: Debug.zip

-
  matrix:
    only:
      - image: Ubuntu
  build_script:
    - |
      echo `pwd`
      echo "Will add build_script later"

test: off
