version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
- Visual Studio 2017
- Ubuntu

configuration:
#- Release
- Debug

platform:
- x64

for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  install:
    - |
      if not exist %USERPROFILE%\vulkan-sdk.exe curl -L --silent --show-error -o %USERPROFILE%\vulkan-sdk.exe https://vulkan.lunarg.com/sdk/download/1.2.131.2/windows/VulkanSDK-1.2.131.2-Installer.exe?Human=true
      CertUtil -hashfile %USERPROFILE%\vulkan-sdk.exe sha256
      echo sha256 should be 7434a39620e425330e3822effbdbefa41ce6e342cd8c610a3c49dc7375f0649d
      %USERPROFILE%\vulkan-sdk.exe /S
      dir C:\VulkanSDK
  build_script:
    - |
      dir
 
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
    - |
      echo `pwd`
      echo "Will add build_script later"

test: off

cache:
  - '%USERPROFILE%\vulkan-sdk.exe'
