name: Github_CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Debug, Release]
        Platform: [x64]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install
      run: |
        export CC=clang-9 && export CXX=clang++-9 && $CXX --version
        cmake --version
        mkdir bld && cd bld
        sudo apt-get update && sudo apt-get install -y libvulkan-dev libglfw3-dev
    - name: Test Vulkan
      run: |
        sudo cat /usr/include/vulkan/vulkan_core.h | grep VkPhysicalDeviceDriverPropertiesKHR
    - name: Build
      working-directory: bld
      run: |
        #export VULKAN_SDK="$(dirname "$(readlink -f "${BASH_SOURCE:-$_}" )" )/1.2.135.0/x86_64"
        #export PATH="$VULKAN_SDK/bin:$PATH"
        #export LD_LIBRARY_PATH="$VULKAN_SDK/lib:${LD_LIBRARY_PATH:-}"
        #export VK_LAYER_PATH="$VULKAN_SDK/etc/vulkan/explicit_layer.d"
        make -j$(nproc)
